// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0gxgRyx2_KOOzQUAskzm9uI7WT3q3DdI',
    appId: '1:961324122350:web:aead28c32849fb2d1cb3ff',
    messagingSenderId: '961324122350',
    projectId: 'flutter-todo-d560e',
    authDomain: 'flutter-todo-d560e.firebaseapp.com',
    storageBucket: 'flutter-todo-d560e.firebasestorage.app',
    measurementId: 'G-TG4PNETXBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaWbaLYDY4Hp1eyd2zXvcop39oMfVCw7g',
    appId: '1:961324122350:android:cec2bb7c8385d2061cb3ff',
    messagingSenderId: '961324122350',
    projectId: 'flutter-todo-d560e',
    storageBucket: 'flutter-todo-d560e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-YJb3Bz-wose9k4agi6BsXUd0KAsZmLg',
    appId: '1:961324122350:ios:f7fa7518e2d63cd21cb3ff',
    messagingSenderId: '961324122350',
    projectId: 'flutter-todo-d560e',
    storageBucket: 'flutter-todo-d560e.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-YJb3Bz-wose9k4agi6BsXUd0KAsZmLg',
    appId: '1:961324122350:ios:f7fa7518e2d63cd21cb3ff',
    messagingSenderId: '961324122350',
    projectId: 'flutter-todo-d560e',
    storageBucket: 'flutter-todo-d560e.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0gxgRyx2_KOOzQUAskzm9uI7WT3q3DdI',
    appId: '1:961324122350:web:16eabd38364b33731cb3ff',
    messagingSenderId: '961324122350',
    projectId: 'flutter-todo-d560e',
    authDomain: 'flutter-todo-d560e.firebaseapp.com',
    storageBucket: 'flutter-todo-d560e.firebasestorage.app',
    measurementId: 'G-G3PY652Y05',
  );
}
